### ISSUE TITLE
latest install and htmlpurifier / (stupid ?) question

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#1044]
Just did a fresh install using composer and got:
```
qcubed/framework suggests installing ezyang/htmlpurifier (dev-master)
qcubed/framework suggests installing fortawesome/font-awesome (^4.6)
```
In former install this was done automatically, how to install these now ?
And how is it included into the framework ?

**Comment by spekary** [comment]
They are not automatically added to the framework because they are not required for the framework.

You can choose not to purify your inputs, or use other mechanisms (PHP has some built-in rudimentary ones), so you shouldn't have to install the purifier.

Also, font-awesome can be taken care of by refering to the public CDN in javascript. So again, its not required, but for off-line access, its nice to have.

Both of these are installable by executing:

```composer require ezyang/htmlpurifier:dev-master```
or
```composer require fortawesome/font-awesome:^4.6```

**Comment by nlomb** [comment]
thanks, 
closing this
