### ISSUE TITLE
error with PHP 7

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#1048]
just upgraded my demo - server to ubuntu 16.04 LTS, this comes with php 7
got the following error:
```
Error in PHP Script /resources/vendor/qcubed/framework/assets/php/_devtools/start_page.php
Uncaught TypeError: Argument 1 passed to QcubedHandleException() must be an instance of Exception, instance of Error given in /usr/data/share/www/.develop/qcubed-demo/resources/vendor/qcubed/framework/includes/error.inc.php:15
Stack trace:
#0 [internal function]: QcubedHandleException(Object(Error))
#1 {main}
  thrown

Error Type: E_ERROR

Source File: /usr/data/share/www/.develop/qcubed-demo/resources/vendor/qcubed/framework/includes/error.inc.php Line: 15

Line 10:    			$this->MultiLine = $blnMultiLine;
Line 11:    		}
Line 12:    	}
Line 13:    
Line 14:    	// Exception and Error Handling
Line 15:    	function QcubedHandleException(Exception $__exc_objException) {
Line 16:    		if (class_exists('QApplicationBase'))
Line 17:    			QApplicationBase::$ErrorFlag = true;
Line 18:    
Line 19:    		global $__exc_strType;
Line 20:    		if (isset($__exc_strType))

Call Stack:

#0 /usr/data/share/www/.develop/qcubed-demo/resources/vendor/qcubed/framework/includes/error.inc.php(194): QcubedHandleError()
#1 (): QCubedShutdown()

Variable Dump: Show/Hide

Error Report Generated: Wednesday, August 3 2016, 1:14:42 AM
PHP Version: 7.0.8-0ubuntu0.16.04.2; Zend Engine Version: 3.0.0; QCubed Version: 3.0.0 Beta Release (QCubed 3.0.0)
Application: Apache/2.4.18 (Ubuntu); Server Name: server-03
HTTP User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 
```

**Comment by vmakre** [comment]
Line 15:        function QcubedHandleException(Exception $__exc_objException) {

change to 
	            function QcubedHandleException(Throwable $__exc_objException) {

i really don't understand this line , but works for me.

**Comment by nlomb** [comment]
@vmakre 
had also to do
```bash
sudo apt-get install php-mbstring php7.0-mbstring php-gettext libapache2-mod-php7.0
```
thanks, now working

**Comment by kukrik** [comment]
At least good to know!
Whether you closing this topic :)?

**Comment by spekary** [comment]
This appears to be a new PHP7 thing, so just changing it to a Throwable isn't going to work. We will need 2 versions of this. Accoring to the docs, the "Throwable" represents anything that can be thrown, and an Error is an internal PHP error. Both of those types are PHP7 only. So, I think what is happening is that PHP7 has made a number of internal PHP errors into things that can be thrown rather than just creating an error and bombing out. The problem is that they created some new data types to do that. 

This problem also indicates that you have a severe error somewhere, something that would cause PHP 5.6 to simply quit and not throw something. 

To fix this, we will need two versions of QCucbedHandleException, and the code that installs this as the exception handler will need to query the version and install the correct one. It will also need to be HHVM aware, since HHVM uses different version numbering, although they may mimic the PHP versioning depending on what they support.

**Comment by nlomb** [comment]
I'm doing some more tests with PHP 7.0, maybe there are some more issues, 
will report them here,

**Comment by vmakre** [comment]
this is from php net 
<?php
// PHP 5 era code that will break.
function handler(Exception $e) { ... }
set_exception_handler('handler');

// PHP 5 and 7 compatible.
function handler($e) { ... }

// PHP 7 only.
function handler(Throwable $e) { ... }
?>

http://php.net/manual/en/migration70.incompatible.php
https://www.quora.com/What-are-some-good-reasons-to-upgrade-to-PHP-7-from-PHP-5-X

So only remove Exception is maybe solution .

**Comment by spekary** [comment]
Yep, that looks like it. Please make a pull request.

**Comment by vaibhav-kaushal** [comment]
Hope this solves the problem.

**Comment by vaibhav-kaushal** [comment]
@nlomb Let's close this issue then? We can create a new one when another problem arises.

**Comment by nlomb** [comment]
OK, closing
