### ISSUE TITLE
Make QGen, QORM and QForms as a standalone libraries

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#30]
Make QGen, QORM and QForms as a standalone libraries

These three parts of qcubed framework can be used on it's own. It can attract more attension and developers not bound to the qcubed framework as a whole.

The qcubed whould use these libraries and benefit from every pull request for them.

**Comment by olegabr** [comment]
@vaibhav-kaushal yes, we need it to be open. The goal is not fulfilled yet. we need to release the 3.0 version, and only then this issue can be addressed.

**Comment by lackovic10** [comment]
guys i don't know if this is the right place to ask, i didn't find a better one, is there a plan to remove magic methods from the generated classes and replace with getters/setters ?
i like the idea from@olegabr to separate core things into components, something like symfony is doing with their components.

**Comment by vaibhav-kaushal** [comment]
I believe that QCubed has been a fully integrated solution while allowing the user (a web developer) the flexibility to override the core at multiple levels. Separating them might attract more people (which is great), but we might be breaking a lot of code and the very idea behind QCubed of being a rock solid platform to do RAD for web, where all components simply, work.

About the question about getters and setters - as such, there is no plan (there is no consensus, even) to remove magic methods. If however, you want to remove them and implement the getters and setters, you are free to. Just modify the templates accordingly.

**Comment by spekary** [comment]
Ditto. I have put some time into thinking about it. The current 3.0 beta has a template hook in it that will allow you to insert functions in your models. Put a ```custom_funcs.tpl.php``` file into your project\includes\codegen\templates\db_orm\class_gen directory, and whatever codegen it does will be added to your models.

If you do getters and setters, I propose we follow the GoLang model of using a function call that matches the name for the getter, and using 'Set'... for the setter. For instance:
```
$strName = $objPerson->Name();
$objPerson->SetName($strName);
```
Getters and setters are much faster than the magic methods, and are very appropriate at the model level, since there are times when speed of access is important, and the HHVM doc even says that the compiler can inline them.

Speaking of HHVM, it would be great if someone could run a project on it and fix some bugs related to getting it to work. I tried a little bit, but ran out of time. Doesn't currently work.

In terms of modularizing the project, that would take some significant work that the architecture wouldn't readily support. If there is interest in this level of work, I propose we port to GoLang. It would be a huge undertaking, but the code would be blazingly fast, and GoLang's strong reliance on interfaces would make it much easier to create a modular ORM, QControl library, Control generators, and more that could be used independently of the framework.

**Comment by spekary** [comment]
I wanted to add that I suggest putting a configuration flag in the codegen_settings.xml file to turn on and off the generation of getters and setters.

**Comment by vaibhav-kaushal** [comment]
For now we can focus on releasing version 3.0. I have been working on the documentation where I can. When the team size grows beyond a handful, we can think of all the good things discussed here.
