### ISSUE TITLE
College project to be done

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#596]
I have talked to a couple of guys via my company. They will be building a college project concerning QCubed. The project is to *improve* database handling in QCubed for PostgreSQL specific data types (such as tsvector, json and jsonb). This work has to be initially written as a plugin. The feasibility of merging it with the core will be explored later after discussion.

Since it is a college project, I cannot talk a lot about it here. However, in case you want to discuss more about it, please shoot your questions. I will be inviting them (the students who will be working on the project) here for comments. I request and hope everyone here will help them.

**Comment by aadityabagga** [comment]
Hi guys,

I am Aaditya and am one of the fellows involved in the project (got the idea from @vaibhav-kaushal)

At the moment we are pretty much newbies in the realm of PHP and QCubed, but we plan to learn enough in the next two-three weeks so that we can start our work.

Our project synopsis can be found [here](https://drive.google.com/file/d/0Bz30QS97FyxJOGtoTWtuLURvQnM/view?usp=sharing).

Thx in advance for your help.

**Comment by neer7861** [comment]
Hi, 

I am Neeraj, one of the fellows involved in the project.

Thanks.

**Comment by spekary** [comment]
That is great! Thank you for your help!

As a plugin, see the plugin_* plugins already posted. All future plugins should be installable by Composer, and that may take a little work to figure that out.

Also, regarding the core, QCubed has had a goal of being database agnostic, and allowing someone to easily move from one database to another database, without changing code. Things that are part of a specific database are abstracted out so other databases can use it. That is why we do not specifically support the MySQL SET type for example, but rather we implement the same functionality using what we call "association type tables", which is combining an association table that gives a many-to-many relationship, and a type table, that is a list of constants.

So, if your work can be abstracted to work for all databases, that would be helpful. For example, you mentioned PostgreSQL json output. I would imagine such a thing could be done in the templates for the model generators, and then all databases could have json representations of the records.

Regarding the templates, the latest alpha3 branch has the ability to add a plugin template by referring to the template in the configuration.inc.php file. You could modify this mechanism to allow an array here so that a whole series of templates could be overlaid. This would allow you to make a database specific series of templates, and someone else to make a plugin of templates for a CSS framework, etc., and they all can be used.

**Comment by spekary** [comment]
Another thought. Our ORM generator has some similarities to the Propel ORM. You might take a look at what they are doing as well.

**Comment by spekary** [comment]
And another thought. We have talked about HHVM here. Probably the biggest and easiest gain for HHVM performance is to have a version of the templates that generate code that is Hack compliant, and maybe even Hack STRICT. You will notice that there are a lot of references to QType in the code, which was an attempt to enforce type checking many years ago. Hack is a new way to do that (though it requires HHVM).

**Comment by aadityabagga** [comment]
Thx @spekary for the ideas.

We have installed and are working with version 2.2.3 (master branch), but will look at the newer plugins (like https://github.com/qcubed/plugin_datatables) and try to make it compatible with both 2.2.3 and 3.0 if thats okay with you.

Atm we are still figuring out how QCubed and PHP works so most of your ideas are probably over our heads!

**Comment by vaibhav-kaushal** [comment]
@spekary Yes, I too think we can extract out the common stuff and JSON is definitely one of them. But since these guys are mostly inexperienced (for now, at least), I think working adhoc on the work at hand will be beneficial for them (since they also have a time-frame to accomplish things). 

When the plugin is built and is ready, the core team can extract things out of the plugin into the core framework. As far as HACK/HHVM is concerned, it's a great idea. I had another fellow who was excited about it as well but he is having some personal issues. Will try to tug him along when both of us get time. 

@aadityabagga Do not *worry* about what @spekary just said. Things will get clearer as you start using and understanding the framework. As you move ahead, you will be able to comprehend his comments much better.

**Comment by aadityabagga** [comment]
Got it, thanks.

Currently reading http://localhost/qcubed/assets/_core/php/examples/index.php

**Comment by olegabr** [comment]
@aadityabagga and @neer7861, you are welcome!
