### ISSUE TITLE
alpha-3: codegen uses in core controls

### ISSUE THREAD

**Issue by vakopian** [qcubed/framework#630]
In alpha-3 many `Codegen_` static functions have been added to core control classes.
I'm not sure why this was necessary, but I don't think QCubed core should have any dependency on codegen. In fact one of my goals is to separate codegen into it's own project separate from qcubed core (and pulled with composer).
Can we move these new methods into some helper classes inside codegen?

**Comment by vakopian** [comment]
I came up with a way to refactor this code to decouple codegen from the core. To see a preview of what I'm proposing please take a look at this https://github.com/vakopian/jqcubed/compare/qcubed:alpha-3.0...model-connector-codegen-refactor
Here are the advantages of this approach:
* core does not depend on codegen
* plugins can still provide custom connectors by creating their own class that extend `ModelConnectorControlHelper` (using the class name convention `ModelConnectorControlHelper_${PLUGIN_CONTROL_CLASS}`)
* The abstract base class `ModelConnectorControlHelper` provides a clear interface of what the custom control needs to implement
* Completely avoid using the `ReflectionClass` and its `hasMethod` facilities.
* Less code in templates when using these helper objects
* Overriding is done with regular class inheritance (rather than the php's static inheritance)

I've only refactored the code for `QControl`, `QLabel` and `QListBox` so far.
If you guys agree with my approach, I'll finish the whole thing and make a pull request.

**Comment by olegabr** [comment]
I like this aproach. Please, show an example of it for some plugin control.

**Comment by vakopian** [comment]
As the _Make Your Own Plugin, Part 1: Writing Custom Controls_ example explains (in `components.php`), to use a plugin control (that does not extend one of the core controls) as part of the code generator, the plugin control class has to define some static methods like `Codegen_ConnectorCreate()`, `Codegen_ConnectorRefresh()`, etc.
With my proposed change, instead of putting these static methods into the plugin control class, the plugin package would have to define a separate class named `ModelConnectorControlHelper_${PLUGIN_CONTROL_CLASS}` that implements the `ModelConnectorControlHelper` interface (of course it could also extend and override one of the existing subclasses in core codegen).

None of the current plugins for alpha3 uses this feature, so I can't really show a good example for an existing plugins. But I definitely like this feature and would use it when I port my projects (which are based on my jQCubed scaffolding) since I use many plugin controls in my custom templates.

**Comment by vakopian** [comment]
BTW, `ModelConnectorControlHelper` is not the best name, so if someone can suggest a better name...

**Comment by spekary** [comment]
I would like to see it too. There are definitely some improvements that could be made, and I am willing to see something that has the codegen at least in a separate but related object. 

However, the code for codegen is in the control file on purpose. Yes, it takes up some space that is only used during codegen, but it is a small amount of space really and will not noticeably affect performance. And yes its a little ugly, but again, if it can be separated to a particular part of the file, then not a big deal.

The controls need to logically know how to generate their own connector code. Please help me understand why you want to separate the control from codegen. What benefit are you trying to achieve? QCubed isn't supposed to be like YII. Codegen is an important and integral part of QCubed. 

Having the codegen be in the control file makes the statement that if you change the control, you must consider codegen impacts and update those too. It also allows the user to subclass a control, and also override some part of the codegen process more easily to get custom behavior in the codegen.

The end result of all that codegen work I did was for the benefit of having a ModelControl editor dialog. It lets you right-click on a control on the screen, and change the type of the control that is being generated for that database field, and the user can choose from a list of control types that support that database field type. It will then present options that are customized to that control type that the developer can set up, and then finally codegen everything. If the controls don't know how to generate their own code, then you have to set up two parallel systems that know about each other, but aren't physically connected. Over time, they will diverge and it will get harder to maintain. I am willing to live with unused code in the controls for the purpose of maintainability in the future, and making the statement that when you create a control, you should consider how it can be connected to the database through codegen.

**Comment by spekary** [comment]
> None of the current plugins for alpha3 uses this feature, so I can't really show a good example for an existing plugins. 

See QDateTimePickerBox.php in the timepicker plugin.

>BTW, ModelConnectorControlHelper

How about just CodeGenerator, though I would swap it to be {ControlName}_CodeGenerator.

**Comment by vakopian** [comment]
Ok, how about
`AbstractControl_CodeGenerator -> QControl_CodeGenerator -> QLabel_CodeGenerator`, etc?

So for example for `QDateTimePickerBox` the class would be named `QDateTimePickerBox_CodeGenerator` and will extend `QControl_CodeGenerator` and will override `VarName`, `ConnectorCreate`, `ConnectorRefresh` and `ConnectorUpdate` methods from the parent.

@spekary, from your comment I gather (as the orginal author of this idea/imp-lementation) you're not objecting to this change. So I'll go ahead and make a full pull request

**Comment by spekary** [comment]
Not objecting, just want to make sure its going to work out with the ModelConnector editor. Also, as I think about it, I am open to breaking them out into a different file. For psr-4 purposes, the file name would be the same as the class name. That will give clarity to the whole thing.

The editor will need to look for a  *_CodeGenerator.php file.

**Comment by vakopian** [comment]
Please review/merge #633

**Comment by vakopian** [comment]
I haven't looked into the ModelConnector Editor yet, not sure how it uses these CodeGenerator classes. Will try it soon

**Comment by vakopian** [comment]
Ok, I see what you mean about the editor now. Closing the PR for now, will re-open after more refactorings.

**Comment by vakopian** [comment]
Reopened #633 after a lot more refactoring.
Note that even though we have lots of ***_CodeGenerator classes now, most of them are autogenerated together with the jquery UI wrappers.

**Comment by spekary** [comment]
Personally, I think it would be cleaner if you kept the GetModelConnectorParams function in the main class. It needs to mirror the __set() magic method, and its easier if its in the file right next to it. It also prevents having a ton of those _CodeGenerator files, so it would be a lot cleaner. And finally, since the ModelConnector dialog is accessible just by flipping a switch, it is not really a CodeGenerator only thing.

#633 is failing the unit tests currently.

**Comment by olegabr** [comment]
+1 for @vakopian solution. The control and the codegen are independend things. we need a Bridge between that two, and it shold be separated from that two too.
And the suggestion for name: QControlCodegenBridge, QLabelCodegenBridge, etc.

**Comment by vakopian** [comment]
#633 is passing the tests now.
@spekary, I'm not a big fan of how we end-up with another big hierarchy of _CodeGenerator classes which mirrors the control hierarchy.
Since `GetModelConnectorParams` mirrors the properties of the control, is there a way to use reflection to implement that method? If (as I suspect) reflection is not enough, perhaps annotations (aka DocBook)?

**Comment by spekary** [comment]
I don't think so. There are subtle differences. Not everything is usable. And, there are the descriptions of what each item does. 

If you move GetModelConnectorParams  back into the control class, that removes about 90% of the new files. 

Also, how would someone subclass one of the generators to override it and have that overridden function chosen instead of the base control's generator? In the old version, you can just implement the method in the overriding class.

**Comment by vakopian** [comment]
> Also, how would someone subclass one of the generators to override it and have that overridden function chosen instead of the base control's generator? In the old version, you can just implement the method in the overriding class.

If you're asking about the current solution in #633, everything is already done with normal inheritance, so that's already handled.

For the "annotations" approach, you're right inheritance/reuse might be an issue. Could mixins/traits help there?

**Comment by vakopian** [comment]
The more I think about it the more I like the idea of using annotations for `GetModelConnectorParams`.
How does QCubed community feel about PHP annotations in general? The larger PHP community is divided - some love it, some hate it, some ignore it. I'm a big believer in annotations as a concept, and I think PHP will eventually get full support for it at the core language level, rather than DocBook.

If there is no strong objection for this (especially considering that this is for codegen only, it does not affect actual runtime), I would like to attempt implementing it with annotations (probably using the doctrine2 annotation processor).

**Comment by olegabr** [comment]
@vakopian, how it would change the tipical development process with qcubed?

**Comment by vakopian** [comment]
for release it would not change anything at all. For development (where you run codegen), composer will bring in the necessary dependencies (in this case "doctrine/annotations") and that should be it, the rest would be in our code

**Comment by spekary** [comment]
GetModelConnectorParams is supposed to be available during the course of development. It might only affect codegen, but codegen happens regularly during development. It should be always present.

Currently, if in the course of using your application, you see something about a control you want to change, you just right click on it, change the setting, then click the button to save and codegen, and you are off and developing again. What used to take minutes, now takes seconds. Whatever your proposing should not impact that. The perceived benefit of having unused code not be in the control file should not trump anything that would cause extra effort in the development process. I definitely should not have to break out into some other tool on the terminal in order to run a pre-processor every time I add a parameter to a control. The current  implementation made it quite easy to change things. Yes, there was some redundancy, but its not all a mirror image, you do have to think about what you are telling the developer for each option.

I am worried, because the refactoring you did is already causing extra effort. To create or override a control, I now have to create and/or manage two files and not just one. If I am looking through the base_controls directory for a particular control, I now have close to double the number of files I have to scan through.

I guess I don't see the benefit of refactoring into separate files or even classes. Certainly performance can't be the issue. And the static methods don't get serialized, so they add no weight to the form state or control for that matter. Is it just aesthetic? The static methods could still use inheritance

> everything is already done with normal inheritance, so that's already handled

Give me an example. Lets say you want all your QTextBox derivatives to use 'text' as the prefix, rather than 'txt'. In the current implementation, I would add this to the QTextBox.class.php file in my projects/includes/control directory:

```
		public static function Codegen_VarName($strPropName) {
			return 'text' . $strPropName;
		}
```
and that is it. How would I do that in the implementation you are proposing?

Also, lets say I would like to add the new html5 'multiple' attribute to email text boxes. Currently, I just add __set and __get options, and then add an item to GetModelConnectorParams. If you are suggesting that instead we put an annotation by the set and get options, and then run a preprocessor to generate a separate file for the GetModelConnectorParams, I really think that is overkill and adds an unnecessary burden to future developers. It really isn't that difficult to add an extra line to GetModelConnectorParams. I think there are bigger issues to solve in the core.

**Comment by vakopian** [comment]
@spekary I think there is a lot of misunderstanding here. So I'll try to address some of your questions.

> The perceived benefit of having unused code not be in the control file should not trump anything that would cause extra effort in the development process.

This is not a "perceived benefit". This is real decoupling of codegen from production code. I don't think I need to explain the problems with such couplings (but I can, if there is need).

> I definitely should not have to break out into some other tool on the terminal in order to run a pre-processor every time I add a parameter to a control

I totally agree, and everything I propose will keep the current way. The goal is to have no change in functionality that you developed. Definitely nothing to do with tools in a terminal.

> I am worried, because the refactoring you did is already causing extra effort.

I understand, but it only ballooned because of the `GetModelConnectorParams` method. This is exactly why I'm looking for a different solution (see below).

> Give me an example. Lets say you want all your QTextBox derivatives to use 'text' as the prefix, rather than 'txt'.

Ok, In your derivative class you override the function:
```php
class QMyFancyTextBox_CodeGenerator extends QTextBox_CodeGenerator {
    public function VarName($strPropName) {
        return 'text' . $strPropName;
    }
}
```
This is more straightforward than overriding a *static* function with a funny name in QMyFancyTextBox.

Even if you leave the coupling aside, just from simple OO perspective these methods (static or not) don't belong in the control classes - they don't describe anything about the control, they are not part of the control interface. They do describe things about the code generation, which is where they belong.

Now about annotations. 

> run a preprocessor to generate a separate file for the GetModelConnectorParams

The annotation processor does not generate any files. It works just like reflection:
```php
$property = new ReflectionProperty('Product', 'name');
$annotations = $reader->getPropertyAnnotations($property);
foreach ($annotations as $a) {
    // get the attributes of the annotation from $a
}
```
Here are a couple of articles that might be useful for people who haven't used annotations in php before:
http://blog.mayflower.de/785-15.12.-Using-custom-annotations-in-PHP.html
http://www.slideshare.net/rdohms/annotations-in-php-they-exist

**Comment by spekary** [comment]
OK, I get it. That generally makes sense.

>  they don't describe anything about the control, they are not part of the control interface

That depends on what you think is a control. If you think of it as strictly a subclass of QControl, then yeah. I am thinking of it more abstractly, as an object on the screen that connects a person with data. Thinking of it that way, then in the implementation, you can have a lot of different types of interactions with the application, including codegenning the interface. QControl is just implementation details. That is my main disagreement with the whole PSR-0/4 thing. They are forcing us to think of files as implementation details, rather than encapsulators of ideas. But I digress.

The annotations you are proposing would be placed in the setters or getters or somewhere else?

Use composer to install doctrine?

You are going to need some kind of mechanism to pick up the MyFancyBox_CodeGenerator class. It may not exist, meaning it should use the parent class, but how will it know what the name of the parent class is? And that might not exist either. Either every control will need a *_CodeGenerator stub class, or you will need to do Reflection on the the MyFancyBox, see what its hierarchy is, and then look for corresponding classes.

**Comment by olegabr** [comment]
@spekary and @vakopian, it seems to me that you both discuss about different implementations of some idea. But! This idea was never described anywere. That leads to all misundestandings. @spekary, please, you, as the original author of this idea, describe it briefly in a wiki.
Ideally, it should be a set of requirements the implementation should fullfill.
My list so far:
1. ability to make a whole codegen profile for my project. ideally, in a one folder, or, even, a single file;
2. controls and plugins should have an ability to specify some defaults for this codegen profile;
3. the way these defaults are specified is not so important, but it should adhere to some best practices without sacrificing develpment process convenience

**Comment by vaibhav-kaushal** [comment]
I have been watching this conversation all along and have got something to say. Since it concerns ORM, I'd like to start from there.

What is ORM? - It maps your tables to programming constructs, like classes and allows you to treat your rows as objects. That is the basic definition. 

What do we do in QCubed for the ORM? We automatically generate the code. **It's important to re-view the code that we generate.**

1. We generate ORM classes (to handle querying against the tables in such a way that ensures that other entities that are connected in the DB are connected in the object as well by using relationships and reverse-relationships).
2. We generate controls which allow us to create, edit and delete entries in the DB (currently the MetaControls). 
3. We support a few nitty-gritties like association and type tables. 

I do not see why we need to separate them from QCubed core at all? 

1. Our Querying System (QQ) is what we use for the ORM classes. You cannot separate/decouple that away. 
2. The generated controls (panels, drafts and meta controls) use QCubed's classes to get the job done. 
3. We would not be able to use type and association tables without QQ at this point either. 

At the same time, someone who wants to modify the controls/ORM logic being currently generated can simply create a new set of templates and do whatever he wants.

I am much younger that you guys ( @spekary  and @vakopian ) and I might be wrong but with what I have seen so far - if you cannot completely decouple things, it's better to couple them even more closely. I hate Yii's codegenerator. When I first looked at it when my friend showed it to me, I laughed like crazy and said to him "wait, I will show you what a code generator is". I ran QCubed and he was listening to me for the next half hour without uttering a word. He was also in the favor of ExpressionEngine which is Paid and he was almost astonished. Why? Because we tightly integrate everything. 

Decoupling does not make a lot of sense to me. Refactoring is fine. Allowing plugins to plug into Code Generation logic is fine but codegen is at the core of QCubed already. If this collapses, I'm ready to switch the framework because then QCubed does not do anything which no other framework does. Yeah, jQuery UI and all would be there but the real value we offer lies in the codegen (as least I think this way). And the easiest way to make it unbalanced would be to decouple things. 

Though a bit philosophical and quite debatable - Apple computers are very complex underneath and does not let me do 20 things that Windows will let me. But it is damn powerful, intuitive and gets job done. Most important part - does not crash every now and then and behaves the way it is supposed to. 

The easiest way to break things is to decouple them. For now, #633 looks lovely allowing everything that we need. So I would not go further but please, decoupling is not what QCubed should do. On that I stand opposed to what @olegabr once mentioned (that we should break into smaller projects). I do care about QCubed's popularity and usage but frankly I care a lot more about how beautifully everything is integrated here. Let's not make it Linux - where they talk all philosophical about how great it is to allow a 1000 things but every single release of every single distribution introduces a myriad of new problems. It is stable only if you un-plug those things which fanboys keep telling are great. Philosophies of Linux fail after meeting reality - which is why they are great for Servers where they do not need to change and have a defined behaviour to a very large extent - once again - stability achieved by integrating things beautifully and stabilising APIs.

Let's keep it like Apple (not the close-source part) - tightly integrated. It might not offer you strange stupid things but it will make sure that work standing atop QCubed will remain extremely stable and rugged. It might be difficult to believe but I was recently contacted by a guy who is running a 5 year old QCodo based ERP solution which he is fine with and wanted some little changes on the templates level. This is what I love about QCubed. This is what I want to keep loving about it.

Great fonts don't make great framework; great code does. And great code is always tightly integrated and well controlled.

PS: I personally feel symfony is the most non-musical framework.

**Comment by vakopian** [comment]
> The annotations you are proposing would be placed in the setters or getters or somewhere else?

Ideally we would place them on getters, but we don't have real getters, and I don't think magic getters would do. But we still have a few choices for this.
* use the `@property` annotations that we already write.
* add our own custom annotation and place it on the properties, so it would look something like this:
```php
class MyFanceBox {
    /**
     * @QCubed\Control\Property(name = "HtmlEntities", description = "Set to false to have the browser interpret the labels as HTML")
     */
    protected $blnHtmlEntities;
}
```
The advantage of the first approach is that our source files stay as is, nothing more is added. The disadvantage is that it's less structured and it only allows us to grab the name, type and description. Also  even when php adds language level support for annotations, this will not be supported.

The second approach is more structured and would allow us to create all the metadata we need. The cost is more added lines.

Considering the information you need for `QModelConnectorParam` I think the second approach is the better route to take.

> Use composer to install doctrine?

Yes, of course.

> You are going to need some kind of mechanism to pick up the MyFancyBox_CodeGenerator class. 

Yes, the assumption is that the `MyFancyBox_CodeGenerator` class is also autoloaded. So when you add `MyFancyBox` to your `app_includes.inc.php` you also add `MyFancyBox_CodeGenerator`

> It may not exist, meaning it should use the parent class, but how will it know what the name of the parent class is?

Yes, that's actually already in the current pull request: https://github.com/qcubed/framework/pull/633/files#diff-017c9c94fa2ca19b167dc1971c9ab47cR828

Now, I wanna clarify one thing about this new proposal. There are 2 parts to this issue. One is the "ModelControl editor" and its related `GetModelConnectorParams` method. This is what I wanna do with annotations. However the rest of the #633 pull request that deals with moving the static CodeGenerator_XXX() methods into their own class should still be done as it's in the pull request. But it will only need a few classes, so will result in a much smaller pull request.

**Comment by spekary** [comment]
All, good discussion. Its clear this feature pulls on the core philosophy behind qcubed a bit. I like the new direction @vakopian is taking with this. As long as its clear and fairly easy to add items to the ModelConnector editor, then I am fine with it. Though, I think in the end the annotations are not going to save all that much typing. As you said, the current getters are not going to be useful for this, and so you basically have to retype the name, the type, and the description of each item into a comment, rather than into an array structure. Seems like more work to implement annotations than its worth. I think we should just save developers the step of having to install the doctrine annotations module, and having us all have to rely on them to keep it updated and working.

Regarding the other breakouts, the CodeGenerator_XXX methods, that works for me.

**Comment by vaibhav-kaushal** [comment]
How about the codegenerator classes be moved in a separate directory. This will save us from confusion and keep things organised!

**Comment by spekary** [comment]
I would vote no on that. Again, we are really getting away from the point in the first place, which was to have the controls control their own link to the database, with the ability to easily manipulate and override that control. The naming convention is enough to prevent the confusion, and there will not be very many files with the QModelConnectorParam dealt with separately.

**Comment by vakopian** [comment]
Let's do this in two phases, which are kinda independent of each other in my view anyway.
* 1st phase - move all the `Codegen_Connector***` methods to the `${CONTROL_CLASS}_CodeGenerator` classes. This does not create too many classes. So I have a pull request to do this #655 
* 2nd phase - we'll think about better ways to handle the `GetModelConnectorParams` later, post 3.0 release (especially since I'm not getting any chance to try implementing the annotation method I described above).

**Comment by spekary** [comment]
I agree with this approach. I took a look and have some questions:

- Why did you not include the "Base" suffix in the various classes to correspond with the name of the matching class file?
- How do I override a method of code generation for a particular kind of control? Please give specific steps.

**Comment by vakopian** [comment]
> Why did you not include the "Base" suffix in the various classes to correspond with the name of the matching class file?

I just renamed the classes to have "Base" suffix, and added the corresponding empty classes without the "Base" suffix, to allow developers to customize them (see bellow).

> How do I override a method of code generation for a particular kind of control? Please give specific steps. 

There are two cases here:
* The control for which you're trying to override the code generator is your own control (not a core control). For example let's say you created your own `MyFancyBox` control. All you have to do to is create a class called `MyFancyBox_CodeGenerator` that extends `AbstractControl_CodeGenerator` (or one of its existing subclasses) and implements your desired behavior, plus register it with the class auto-loader. That's it. Everything else is as you had before.
* The control for which you're trying to override the code generator is one of the core controls. For example `QLabel`. In this case you'll have to actually modify the `QLabel_CodeGenerator` class (which is currently empty) and override the methods from the base class (`QLabelBase_CodeGenerator`) which you would like to customize. This is similar to other customizations of core functionality in QCubed.
