### ISSUE TITLE
Testing Beta 3.0

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#694]
Hello all (especially @spekary ),

I have started the testing of beta 3 branch and have achieved initial success (installed and displayed the home page of the site). So I know that the base framework is at least working.

In my project which currently depends on 2.2, I had installed the confirmation dialog box plugins. Is there a guide to migrate/write the plugins for the new version?

**Comment by kukrik** [comment]
Hi, I was testing yesterday. I will also work well ... I tried this beta 3 branch also plug-ins do not work well for me at the plugin_bootsrap. I've written to @spekary repository...

PS.  At plugin_datatables are no examples. They might be there...

**Comment by vaibhav-kaushal** [comment]
@spekary So far so good. QCubed has a major restructure against 2.2 but after getting the reasons why those were done and understanding the new structure, I am finding it good and so far it has been sailing me smoothly.

**Comment by vaibhav-kaushal** [comment]
@spekary How do I use QWatcher system?

**Comment by spekary** [comment]
See the examples page on it.

**Comment by kukrik** [comment]
I'm jealous that you have answered the @vaibhav-kaushal 's question :(.

Do you have some free time to answer my question?

**Comment by spekary** [comment]
Yours are harder. I will get back into the bootstrap items in a while. Was there anything specific?

**Comment by kukrik** [comment]
The screenshots is out there:
1) https://cloud.githubusercontent.com/assets/2853034/7849770/b8ac9768-04e1-11e5-8a16-ac5eac1ff6d4.png
2) https://cloud.githubusercontent.com/assets/2853034/7849768/b8a73174-04e1-11e5-935f-908b81735ddc.png

Do they not say anything ??? I would venture to guess that the code level, is there something missing?

**Comment by spekary** [comment]
First one is saying that it can't find the class. Did you install using Composer? At this point, composer is mandatory for plugin installations, since it is providing the auto-loader. It could be a problem with the names too. I haven't looked at that in a bit.

The second one is probably a newer bug. It is thinking it should open a file with a name that is a space. You have to step in and see why.

**Comment by kukrik** [comment]
Please note
1) The first line of 3-5 erroneous file names
and https://github.com/qcubed/plugin_bootstrap/blob/master/examples/bootstrap.php
The first line of 3-4 erroneous file names
https://github.com/qcubed/plugin_bootstrap/blob/master/examples/forms.php

Whether I'm wrong when I corrected as follows:

require_once ('../includes/Bootstrap.class.php');
require_once ('../includes/NavBar.class.php');
to
require_once ('../includes/Bootstrap.php');
require_once ('../includes/NavBar.php');

I used naturally Composer!

I can start again from scratch?

**Comment by spekary** [comment]
Remove them, since the auto-loader will find them.

**Comment by kukrik** [comment]
I'm doing right now! I will report back to how it goes...

**Comment by kukrik** [comment]
The same results as in the past :)

Are you sure you included the names of the files are still correct?

I added screenshots:
![image](https://cloud.githubusercontent.com/assets/2853034/8071485/32313324-0f13-11e5-94da-f4a31e9495a5.png)
![image](https://cloud.githubusercontent.com/assets/2853034/8071492/3f3f0bb8-0f13-11e5-9410-c2eae9f3497f.png)

**Comment by kukrik** [comment]
@spekary, You may have used a personal repository. Please try to use according https://github.com/qcubed/plugin_bootstrap/blob/master/README.md.

PS. I know that that had created a great plugin :)

**Comment by kukrik** [comment]
@spekary! I want to clarify your recommendation "Remove them, since the auto-loader will find them". Where is the auto-loader, which must be removed? Thank you in advance!

**Comment by spekary** [comment]
Remove the "require" lines. The composer auto-loader will load those files.

**Comment by kukrik** [comment]
@spekary. I got to work both sheets (bootstrap.php and forms.php). I'll give a brief summary.

Please remove these lines as follows:
1) examples/bootstrap.php lines 3-5,
2) examples/forms.php lines 3-4,
3) includes/Navbar.php line 5,
4) includes/Button.php line 6,
5) includes/Control.trait.php line 5.

Correct off, others praise you ☺!

**Comment by kukrik** [comment]
@spekary! Hopefully, I give you a bit of help: https://github.com/qcubed/plugin_bootstrap/pull/3

**Comment by vmakre** [comment]
install problem of beta 3 via composer. Some error as 
>Warning: Ambiguous class resolution, "SimpleReflection"

I removed simple reflection from json but no qcubed library in vendor.
@spekary  are you sure readme file is ok?.
Why the line from alpha 3
>"qcubed/framework": "dev-alpha-3.0", 

 is removed from beta 3 json file?

**Comment by spekary** [comment]
The ambiguous class resolution thing is just something to ignore. Its a problem with the library we are using. The solution is to ask the library maker to fix it, which I have not done.

> Why the line from alpha 3

> "qcubed/framework": "dev-alpha-3.0",
> is removed from beta 3 json file?

The beta 3 installation process is different now. You must install the app-starter project as described in the readme, rather than directly installing qcubed/framework. That will also install our custom installer, which moves files to the right place, and supports plugin instllation.

Its not well documented on the Composer web site, but Composer essentially has two usage models. One is a top level installer, and another is a library/plugin installer. The two are conceptually really different because of certain limitations in Composer. The composer.json file in the beta 3 directory is now setup as a library installer, and expects to be included by the app-starter project, and the composer.json file in the app-starter project is the true master installer for QCubed. Its just the way Composer wants to work. Other frameworks do the same thing because of these issues. I tried to push the Composer people to make some changes so that we wouldn't have to do it this way, but they wouldn't budge, even though many other people were asking for the same thing.

**Comment by vmakre** [comment]
ok i think now will be ok.
You can simply change qcubed\app-starter  with qcubed default project .

**Comment by vaibhav-kaushal** [comment]
So far everything is working properly (I am already writing a generic migration guide, which can be used by most people). What is left now to make a RC/Final release?
