### ISSUE TITLE
Assets not in project folder? 

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#696]
We are targeting the entire installation be done via composer. For that to happen we have to have the assets ion the publicly accessible directory aand keep the rest in the vendor directory. However, it appears to me that the current beta implementation keeps the assets (especially the jquery library :astonished:)  in the vendor directory.

I think we need to move the assets and JS libraries in the project folder. Am I missing something here?

**Comment by spekary** [comment]
The vendor directory is what contains the core code. This is code that will be overwritten when you do a composer update. Its also code that SHOULD be written when you do a composer update. All the core assets should be overwritten, so they stay in the vendor directory. I think you are confusing the idea of  composer install vs. a public deployment.

For a deployment, the assets need to be publicly accessible, and the other code should not be for security. We have had a discussion on the forum about creating a script to do deployment, but no one has done it. Doing a deployment script would require asking for deployment location and credentials to get there through ftp, and then rewriting the configuration.inc.php file while also uploading the site. Its not trivial. One thing that could make it easier is to change the current configuration.inc.php file to look for a different file when in production mode so that there is no actual rewriting of configuration.inc.php, but rather just a generating of different file.

**Comment by vaibhav-kaushal** [comment]
I understand the thing about security part. My idea was that we take all the public stuff in the project directory only and move the 'vendor' directory. That will ensure our own framework as well as other supporting libraries are in one directory which we can secure. That was the thing I had in mind. 

Whatever I said, I said with that presumption in mind. If we can structure things in accordance, the maintenance script we are thinking about would be much smaller (i hope).

**Comment by spekary** [comment]
Actually, I think maintenance might be more difficult, because you would be mixing the files together. Its probably not that big a deal, but it would be nice to be able to visually compare two directories for equality. To really answer this, we would need some idea of where we are headed. We could do one of two things at DocRoot:

- assets
  - qcubed
    - js
    - css
    - fonts
    - images
    - php
  - plugin A
    - css
    - js
  - plugin B
    - css
    -js
  - project
    - css
    - images
    - js

Or, put everything together. Putting it all in one directory makes it hard to know if there are stale files in there, and where they are coming from. However, if deployment always erased the directory before rebuilding it, that would not be such a problem. 

- assets
  - js
  - css
  - fonts

The other problem is name conflicts. We cannot always know that a plugin css or js file would not have the same name as a different plugin's files, since these files often come from 3rd parties and we do not build them. Some plugins are very particular about their names. The first structure prevents file name collisions.

**Comment by vaibhav-kaushal** [comment]
I think that the first one is great. We can always ask the user to copy-paste from vendor directory if that is needed and thus help him/her override certain features safely too.

**Comment by vaibhav-kaushal** [comment]
I think I am slowly getting the whole idea of this new design. It looks great so far. Leaving this issue open for some time.

**Comment by vaibhav-kaushal** [comment]
I think I have understood how they are working. A member in my team is writing deployment script for our project which I believe can be used by QCubed too (not sure though how it would turn out to be). 

Closing this thread though.
