### ISSUE TITLE
QQNode class for Type Tables in version 3.0?

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#779]
I have noticed that now we are creating QQNode classes for TypeTables which were not being created in version 2. As far as I can see, it is for allowing querying on those tables (since they can have more info than just the type!). Is there any other points where these classes are being used (or can be used?).

**Comment by spekary** [comment]
Yes, the expansion for TypeTables allows them to be included in the codegen process easier. A foreign key to a type table results in a list control that lets you select from the available options. It also allows columns to display the Name of the type, rather than just the number, and allows multiple names to be displayed when getting to the type table through an association table.

QQNodes are also being included in the QControls. Currently, its being used during codegen so that the control knows how to access the data its linked to. I am working on a new QDataTable that is built on QSimpleTable, and that will use the QQNode to help columns know how to display their data.
