### ISSUE TITLE
Use the new HTML5 based date input

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#789]
```
<input type="date" />
```
Opens up a good input control on Chrome. I am wondering why aren't we incorporating this into QCubed?

**Comment by spekary** [comment]
Because this framework tries to be as cross-platform as possible, and we do things that will work consistently on all browsers. type=date is not supported by Safari, Firefox or IE. However, it has relatively good support for phone browsers (except IE), so it might something specialized for mobile.

Seems like something that someone should do in their own implementation in a platform specific way. Not a framework thing I think.

**Comment by vaibhav-kaushal** [comment]
Okay, then we should wait for the implementations to get available across platforms!
