### ISSUE TITLE
Problems with QControlProxy

### ISSUE THREAD

**Issue by vaibhav-kaushal** [qcubed/framework#803]
**This is a detailed description of problems with QControlProxy and its a bit long.**

I have multiple pages on my site which heavily depend on QControlProxy. Not only this, the paginator (QPaginator) also uses QControlProxy to render the links for the pages. 

The problem is - I have a page with a panel that displays a range of dates (usually a week). Each date is clickable and the click handler is handled via a proxy. There are two buttons to go to the next and previous weeks. When either of the buttons are clicked, I simply regenerate the panel with new dates as parameters and call a ```Refresh()``` on it. 

The way AJAX rendering method (RenderAjax, precisely here: https://github.com/qcubed/framework/blob/beta-3.0/includes/base_controls/QFormBase.class.php#L743 ) works, newly created QControlProxy within the panel will never have its JS event binding statements sent to the browser. This is because QControlProxies are not set in the Rendered state by default. 

This issue causes such panels (which create QControlProxy in response to an AJAX call) to fail because the event is never bound to the action in the browser. So, I replaced the existing logic with this: 

```
            foreach ($this->GetAllControls() as $objControl) {
				$strScript = '';
				if ($objControl->Rendered) { // whole control was rendered during this event
					$strScript = trim ($objControl->GetEndScript());
					$strControlIdToRegister[] = $objControl->ControlId;
				} else {
					if($objControl instanceof QControlProxy){
						$strScript = trim ($objControl->GetEndScript());
						$strControlIdToRegister[] = $objControl->ControlId;
					} else {
						$objControl->RenderAttributeScripts(); // render one-time attribute commands only
					}
                }
				if ($strScript) {
					QApplication::ExecuteJavaScript($strScript);
				}
				$objControl->ResetFlags();
            }
```

But now the problem is that if the ControlProxy is **not** recreated (such as in the paginator's page number links), the event handling script is sent everytime the AJAX request is made, hence effectively doubling the number of times the bound action is run every time a new AJAX request is fired. So for paginator:

The first page change triggers 1 request. This request brings in the binding script too.
So for the second page change, 2 successive requests are fired! Each of these requests will bring 1 copy of binding script as well.
On third page change 4 requests will be fired and 4 new events are bound!

This goes on. Following this pattern, on the 10th page change, 2^10 = 1024 requests would be fired. This is enough to bring down a server! Hence, my solution here is not a solution.

This is a teething issue for me at the moment. I haven't pulled in the QQuery refactorings or anything after that, so till then, everything was working (except #802 which is yet to be merged).

Also, the paginator's "Next" link is not being rendered sometimes.

![consult issue](https://cloud.githubusercontent.com/assets/2824682/10783872/cbf6056c-7d80-11e5-956f-87cf01451c4a.png)

**Comment by spekary** [comment]
If I understand you correctly, you are creating new QControlProxy objects during an ajax refresh, because the QControlProxy is a member variable of a panel that your are creating during ajax drawing. That is definitely not what proxies are for. I suggest you do one of two things:
- If you really want a proxy, create it in the form, and then pass it to your panel so that you can reuse it.
- Don't use a proxy. Use a QButton instead, since it was designed to do this kind of thing.

When you delete the old panel, you must remove the controls from the form first. That is why when you did your fix, you were seeing multiple scripts being attached. Those old proxies were still in the form, recreating their scripts. This is true of any situation where you are creating new objects during ajax refresh. You have to be careful to either reuse the prior objects, or remove them from the form. The PHP garbage collector can't get rid of them until they are removed from the form. Otherwise, your formstate will fill up with old, unused objects and waste memory.

Your fix could work too, but it needs to be combined with detecting that the proxy was drawn. Something like:
```
						if (!$objControl->OnPage) {
							$strOut = sprintf('$j("#%s").on("%s", "[data-qpxy=\'%s\']", function(event, ui){%s});', $objControl->Form->FormId, $strEventName, $objControl->ControlId, $strToReturn);
							$objControl->OnPage = true;
						}
```
in RenderActions, but then OnPage would have to be writable. I recommend simply finding a way to not create a new proxy during ajax refresh. 

If you can create a reproducible case of the Next link not being drawn (put it in qcubed/framework/assets/tests), I will take a look.

**Comment by vaibhav-kaushal** [comment]
Okay. So here are my problems:

The application where this thing works (the week panel) contains only one QForm which handles all kinds of requests. The QForm detects the resource that is required and responds accordingly. Everything else in the application is a QPanel. So technically, if I have to work with proxies, there is just one form which I will have to adjust according to my requirements and that one's already pretty complicated. But yes, your suggestion makes sense. I can have an array of proxies and then I can use them on different pages (some pages use more than one proxy).

There is no way I can use a QButton over there. The UI would be really bad if I do. I can try using QLabels though and they would not hurt me, probably. 

Let me revert back my changes, fix the pages and then I will get back to you. I suspect my changes were the ones which made the next link invisible (or whatever happened with them).
