### ISSUE TITLE
Namespaced QForm

### ISSUE THREAD

**Issue by dmarkic** [qcubed/framework#819]
Hello all!

I'm testing qcubed-3 and some other stuff and I've noticed that if my QForm is in Namespace, (e.q. Vendor\Something\Form) qcubed will not work. It's because any javascript that renders FormId will render it like this:
qc.pA('Vendor\Something\Form', ...);

Which basically means, that qcubed.js will receive this as string "VendorSomethingForm". So to overcome that, I had to use addslashes() on action: eg: 
```php
return sprintf("qc.pA('%s', '%s', '%s#%s', %s, '%s');",
				addslashes($objControl->Form->FormId), $objControl->ControlId, ...
```
And this will render it like this:
```php
qc.pA('Vendor\\Something\\Form', ...);
```
And further, I think officially '\' char is not allowed in element Id, but anyway, jQuery does support selectors with '\' in it, but they have to be escaped. So I had to add another escape of '\' char to qcubed.js. For example:
```javascript
    postAjax: function(strForm, strControl, strEvent, mixParameter, strWaitIconControlId) {
        strForm = strForm.replace(/\\/g, '\\\\');
```
That way, namespaced QForm is working. 

Was this never an issue for anyone? Would this fix be OK? Non-namespaced classes are not affected by this.

Any thoughts?

Kind regards,
Dejan Markic

**Comment by spekary** [comment]
This is a new issue as far as I know, probably because no one is namespacing their app. The problem is a typical programming mistake - using one thing for two separate purposes. In this case, the name of the class is also used as the html form tag id. 

The whole form id is a little wonky at this point. Currently, QCubed only supports one qcubed form in a window. I believe the form id is there for situations where there might be multiple forms due to mixing some kind of 3rd party app with a qcubed form, or in preparation for the day when multiple forms would be supported. It also appears to be used as a kind of protection against trying to recreate a form state for the wrong type of form, though that is rather unlikely to be an issue. I suspect all that code was written long ago at a time when PHP didn't have the reflection capabilities it has now.

The simple fix appears to be to remove the 2 lines at the top of FormBase::Run that checks that strFormId is the name of a QForm class. Then, you can pass in to Run any strFormId you want to use. I haven't tried it, but from a first glance it should work.

**Comment by dmarkic** [comment]
It would not work that easily, as qcubed.js uses FormId for everything (eg pA(FormId, ... ) pB(FormId, ...) and ofcourse, form is rendered with this Id.
Basicaly it just fails to post any data, because qcubed.js cannot find the form by Id. It works by simply addslashes(addslashes(FormId)) to every form Id that is outputted as HTML.

**Comment by spekary** [comment]
Maybe an example to better describe what I am saying. You specify the form id on a form through the FormBase::Run command. That is also what loads the template associated with the form object. So, for the form you mention above, I assume you are doing this at the bottom of your Vendor\Something\Form.php file:

```
Vendor\Something\Form::Run('Vendor\Something\Form', 'mytemplate.tpl.php');
```
and you are saying you are having problem with the slashes in the string that is the first parameter to the Run command. That string is what becomes the html id of the form tag, and also is used to associate all the javascript commands (or should be, if not and some piece of code is instead using the form class, that is a bug). That string is also saved in the form as ->strFormId. 

I just submitted a pull request #820 that will let you do the following instead.

```
Vendor\Something\Form::Run('myFormId', 'mytemplate.tpl.php');
```
"myFormId" should then appear in all the javascript, rather than the class name with all the slashes.

The main issue was that the original code was written long ago in a day when get_called_class() didn't exist, so there was not an easy way to create a new form object without having the name of the class in a string.

**Comment by spekary** [comment]
I found a regression problem with this bug fix. I am redoing this seemingly simple fix, as I found a situation where it will not work. If someone intercepts the Run function at QForm, and passes it on to the parent, the get_called_class function will return QForm, rather than the subclass. 

I am moving strFormId to an optional 3rd parameter, and reinstating the first param as the form's class name.

See #839
