### ISSUE TITLE
Test Bit with QJqCheckBox type is broken

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#867]
In the `project/forms/type_test_edit.php` draft the `Test Bit` field with type QJqCheckBox does not work as expected. It shows no button and no checkbox

**Comment by spekary** [comment]
Need more info. Not sure what you are referring to. Are you talking about TypeTestEditPanelGen.class.php? That is a QCheckBox as far as I can tell. Did you change it?

**Comment by olegabr** [comment]
http://localhost/example.com/project/forms/type_test_edit.php. Choose QJqCheckBox as a ControlClass, save and regenerate. The effect would as I described: no checkbox and no jqbutton, just a text label with no ability to call the editor dialog to change the type back.

**Comment by spekary** [comment]
Got it. Yes, this is in a sense, correct behavior. The particular problem here is that no ->Text has been assigned the button, and so there are no words to display for the checkbox. When there is no text for a checkbox, JQueryUI will not create a button. See the JQ UI Widgets example for examples of how to set up a QJqCheckbox. The bigger issue is that there are ways to to set the codegen options such that the only way to fix them is to directly edit the codegen_options.json file, and this is one of them.

Some improvements that need to be made:
- QCheckbox, QButton, and QRadioButton need a GetModelConnectorParams() function so that the Text and Label params can be set in the editor dialog, as well as other options.
- The system needs to be changed so that Labels can be right-clicked to bring up the control editor. Right now, you can only right click the control itself, and if the control is hidden, you can get a problem like the one you saw.

I think those two improvements could be 3.0.1 enhancements for after release.

**Comment by spekary** [comment]
Fixed in #1016 and #1012
