### ISSUE TITLE
Codegen error log

### ISSUE THREAD

**Issue by vmakre** [qcubed/framework#872]
When i am generating codegen code from a lot of tables with errors , i have problem because error don't shows which table is problem. I know about id primary keys etc. but when i am connecting codegen with someone's database i need a information about where codegen stopped instead of entering in autogenerated code and look what is generated.  I don't have info about error i think it is codegen job not php error .At first will be good to see in what table is problem without description .

**Comment by olegabr** [comment]
please, attach an SQL example to generate errors from

**Comment by vmakre** [comment]
Undefined variable: strErrorinformation
Error Type: E_NOTICE
Source File: D:\xampp\htdocs\frameworks\qcubed-beta3-test1\vendor\qcubed\framework\includes\database\QSqlServer2005Database.class.php Line: 553

Line 548:    
Line 549:    		public function FetchArray() {
Line 550:    			$strColumnArray = sqlsrv_fetch_array($this->objSqlSrvResult);
Line 551:    			if ($strColumnArray === false) {
Line 552:    				// Determine the errorinformation
Line 553:    				$this->GetErrorInformation($strErrorinformation, $strErrorCode);
Line 554:    				throw new QSqlServer2005DatabaseException($strErrorinformation, $strErrorCode, $strNonQuery);
Line 555:    			}
Line 556:    			return $strColumnArray;
Line 557:    		}
Line 558:    
 This is error , database is MSSQL with some tables without primary and id columns. I know error is because of this but i can't see error information on screen.Or maybe i need to disable php E_NOTICE errors ?

**Comment by matthiaz** [comment]
@vmakre The notice you are receiving only happens when there is an error. The actual error isn't being shown because of it. 
This is because the variables are being passed as reference but they aren't initialized yet.
I made a pull request to fix this. So if this gets merged by one of the core developers, it is probably fixed.
https://github.com/qcubed/framework/pull/873

That said: this doesn't fix your codegen. This will only allow you to see the error. I don't know it if has to do with the lack of a PRIMARY KEY. But QCubed heavily relies on PRIMARY KEY columns so if it all possible, I would suggest adding them (in general this is a good idea anyway). I usually add a PRIMARY KEY column "id" with autoincrement.

**Comment by vmakre** [comment]
I know the reason of problem  but i can't see  what table is bad, because of php error  not codegen showing some info.

**Comment by olegabr** [comment]
fixed in #873
