### ISSUE TITLE
The HTMLPurifier protection with some tags allowed does not works

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#880]
The HTMLPurifier protection does not works. It works with default settings, but fails to protect if some tags are allowed: Textbox protected with `QCrossScripting::HTMLPurifier` with a set of tags that's allowed (ex. `<b>`, `<i>`)

Moved from issue #869

**Comment by vaibhav-kaushal** [comment]
Has this started working?

**Comment by vaibhav-kaushal** [comment]
@olegabr How to reproduce it. The problem you have described in the original post is not clear enough to me.

**Comment by olegabr** [comment]
Try this example: http://examples.qcu.be/assets/_core/php/examples/basic_qform/xss.php
The part titled with "Textbox protected with QCrossScripting::HTMLPurifier with a set of tags that's allowed (ex.<b>, <i>)". it works for the qcubed 2, but it was broken in qcubed 3. I don't know if it works or not now.

**Comment by spekary** [comment]
It appears to not be working. It pops up the dialog, and is not supposed to.

**Comment by spekary** [comment]
The problem is the optimizations in QCubed3. Since the text is coming from the program, when you click the button, there is no change in the text, so the text is taken from what was given to the control from the PHP side. If you make any change to the text in the browser, and then click the button, it will be correctly processed. So, this is not really a problem with the control, but really with the example, since HTML Purifier is designed to filter text coming from the browser, not from the PHP side. The example should perhaps instruct the user to type something in.
