### ISSUE TITLE
V 3.0 codegen missing "?>"

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#899]
found that in some gererated files the closing "?>" is missing,
examples from demo
* LoginListGen.class.php
* LoginEditDlgGen.class.php
* LoginEditPanelGen.class.php
* LoginListPanelGen.class.php
* LoginEditDlg.class.php
* LoginEditPanel.class.php
* LoginListPanel.class.php

**Comment by matthiaz** [comment]
@nlomb 

the closing ?> tag is optional and it is best not to add it at the end. I always remove any closing tag I see.

quote from php website: 
 If a file is pure PHP code, it is preferable to omit the PHP closing tag at the end of the file. This prevents accidental whitespace or new lines being added after the PHP closing tag, which may cause unwanted effects because PHP will start output buffering when there is no intention from the programmer to send any output at that point in the script. 

http://php.net/manual/en/language.basic-syntax.phptags.php

**Comment by nlomb** [comment]
thanks,
didn't know that ...
so we should remove them everyware ?

**Comment by spekary** [comment]
It is actually a requirement of one of the PSRs to remove it. We are not PSR compliant or trying to be at this point, so for now, lets leave it alone and simply make it optional.

**Comment by nlomb** [comment]
ok, forget this ...
will close this issue
