### ISSUE TITLE
Encoding of non-string values for data passed to javascript

### ISSUE THREAD

**Issue by koopa** [qcubed/framework#913]
Is there already a way to encode strings as actual javascript objects?
For example consider this code in a subclass of QDialog: 
    
`$this->Position = ["my"=> "center", "at" => "center", "of" => "window"];`

Here instead of "window" getting encoded as a literal string we want the string to be unwrapped from the quotes, so the result is `..., of: window}` rather than `..., of:"window"`.

Is there already something in qcubed to allow for such a thing, maybe a prefix to use?
My example could become "js:window" and then QCubed knows it must not convert this to a string but instead use is as a javascript symbol name.

**Comment by spekary** [comment]
Yes, this comes up from time to time. See QJsVarName in JavaScriptHelper.class.php. 

Its a bit more complicated than just sending back a non-quoted string. Ajax redraw gets sent back through as json, and json does not have an easy way to express a non-quoted string. The QJsVarName will wrap your string when sent via ajax, so that when it gets unwrapped in qcubed.js, it will be treated as a global variable. "window" is perfect for this.

**Comment by koopa** [comment]
Sounds great, thanks for the information!
