### ISSUE TITLE
help needed for QDataGrid2_CheckBoxColumn

### ISSUE THREAD

**Issue by nlomb** [qcubed/framework#929]
just looking for an example for usage of:

QDataGrid2_CheckBoxColumn

thanks

Norbert

**Comment by spekary** [comment]
This is a good request, and part of the general need to update the examples for QDataGrid to be reflective of QDataGrid2. We should keep it open until we take care of this.

**Comment by nlomb** [comment]
ok, maybe I try myself one day

**Comment by nlomb** [comment]
got "QDataGrid2_CheckBoxColumn" displayed in a QDatagrid2 doing this:
```php
protected function CreateCheckBoxColumn($strName, $objNodes, $intColumnIndex = -1) {
	$objColumn = new QDataGrid2_CheckboxColumn($strName, $objNodes);
	$objColumn->HeaderCssClass = 'sortable';
	$this->AddColumnAt($intColumnIndex, $objColumn);
	return $objColumn;
}
```
and calling this in "CreateColumns" - function


but how to connect the checkboxes to data in table ?

**Comment by spekary** [comment]
This is a bigger question than you might think. It depends a bit on what you are doing, but checkbox columns are quite tricky when you think through all the options. And, QDataGrid2_CheckBoxColumn can use some work to enable better options for this.

First, you have to ask yourself what you are doing with the column. Sometimes, the column is used to select items to perform an action on. That is the default, and QDataGrid2_CheckBoxColumn does this automatically, storing the state of the checked rows in the session. When you want to know what columns got checked, call `GetCheckedItemIds`. There currently is no  `SetCheckedItemIds`, but that could be added pretty easily. 

If you are displaying a boolean value and you want to show a check to indicate a true value, QDataGrid2_CheckBoxColumn  is not the right thing to use. Instead, use a callable column and return an icon like a check icon found in FontAwesome. (Perhaps we should create a column to do just this?)

If you actually want the user to be able to edit database data by checking in the column, there are two options.
## You want to save the data after the user presses some button, like a Save button. 
This is where things get tricky. The data grid is designed to only show data that is visible, using a paginator to let the user page through all the data. So it can't really know what is the complete set of checked and unchecked items until the user scrolls through everything. 

What needs to happen is the data grid keeps track of only the changes the user has made, and then presents a method to return only changed data that needs to be updated in the database. It does not do this currently. This isn't the best scenario, because with a large data set, it is easy for the user to forget what has been checked or unchecked. Someone could add this to QDataGrid2_CheckBoxColumn, but again, its not the best UI just having a checkbox. It might be good to have an additional indicator or class added to the checkbox to visually indicate that the data has changed. To do this, GetCheckboxParams needs to query from its group of changed items, and if not there, use the inherited value.

This isn't currently supported, but could be added if needed without too much trouble.

## You want to save the data in the database immediately when a checkbox is clicked.
There are currently two options.
1.The easiest is to create a subclass of the column, and override the SetItemCheckedState and GetItemCheckedState. SetItemCheckedState should update the database, and GetItemCheckedState should return true or false for the checked state, looking in the passed item, or
2. Call `SetCheckParamCallback($callable) ` and pass a callback that will set the 'checked' index in the returned array to the value of the checkbox. Use 		`$datagrid->AddAction(new QSimpleTableCheckBoxColumn_ClickEvent(), new QAjaxControlAction ($this, 'CheckClick'));` on the data grid to detect the click event and update the data.

**Comment by nlomb** [comment]
thanks a lot for the detailed reply.
Yes, found out it's tricky, that's why I asked here ...
did not realize that CheckboxColumn was not made for displaying / changing booleans in a table,
but that's just what I want to do, so I will have to find another solution, I think I will try it using a callable column.

**Comment by spekary** [comment]
For display only, use FontAwesome's check. But you said display/changing. It IS made for changing, so if you are allowing the user to change it from the table view, then this is the correct thing to use.

**Comment by nlomb** [comment]
just tried to do this with method 2 "SetCheckParamCallback($callable)" and "$datagrid->AddAction(new QSimpleTableCheckBoxColumn_ClickEvent(), new QAjaxControlAction ($this, 'CheckClick'))", but how can i get the item into $callable ?

Is there such a callback also available for NodeColumns ?
For I'm in Germany I will habe to translate decimals from "113.25" to '123,25" and back.

**Comment by spekary** [comment]
See QSimpleCheckboxColumn::GetCheckboxParams. The item is passed to the callable.

For other types of columns, you have to callbacks available. See QAbstractSimpleTableDataColumn:
- PostMethod can be set, to call a method on the $cellValue if it is an object.
- PostCallback can be set to call any function. The value returned is the cell value. And it is passed the original cell value. 

Most columns inherit from QAbstractSimpleTableDataColumn.

```
public function FormatNumber($fltValue) {
    return number_format($fltValue, 2, ',', '.');
}
```

and

```
$objColumn = new QNodeColumn('Column Title', QQN::Table()->Column);
$objColumn->PostCallback = 'FormatNumber';
```

**Comment by nlomb** [comment]
Hi, thanks for the reply.

At first I thought the old QDatagrid was easier, but this is much more straightforward.
finally got the callback working, had to make the callable static ...

but: cannot find the "FormatNumber" function, will create it myself just as needed

**Comment by spekary** [comment]
FormatNumber was an example of a callback. Its not in QCubed.

**Comment by nlomb** [comment]
finally got it working, was tricky but I learned a lot about V3.0.
thanks for the help, have a nice weekend
Norbert
