### ISSUE TITLE
Proposal to add encoding "UTF-8" Database Connection

### ISSUE THREAD

**Issue by kukrik** [qcubed/framework#936]
Umlauts problem is always a problem! In English language not problem.
What do you think of this?

Here: https://github.com/kukrik/framework/commit/74765c93ade6f6f5998c6c0b5af7762bae360ca3

**Comment by nlomb** [comment]
I think it's a very good idea, since utf-8 is recommeded by W3C

from wikipedia:
UTF-8 is the dominant character encoding for the World Wide Web, accounting for 86.5% of all Web pages in March 2016 (with the most popular East Asian encoding, GB 2312, at 0.8% and Shift JIS at 1.1%).[4][2][5] The Internet Mail Consortium (IMC) recommends that all e-mail programs be able to display and create mail using UTF-8,[6] and the W3C recommends UTF-8 as the default encoding in XML and HTML.[7]
 
just tested the solution from
https://github.com/qcubed/framework/issues/935#issuecomment-198752693
works with:
```
define('DB_CONNECTION_1', serialize(array(
	'adapter' => 'MySqli5',
	'server' => 'localhost',
	'port' => 3306,
	'database' => 'my_database',
	'username' => 'my_dbusername',
	'password' => 'my_dbpassword',
	'caching' => false,
	'profiling' => false,
	'encoding' => 'utf8')));
```
had to set "utf8" instead "utf-8" in screenshot.
would have saved me a lot of searching and debugging, 
did not expect that this parameter would matter if everything else in
"php.ini", "mysql.conf", "apache2.conf" etc. was already set to "utf-8"
