### ISSUE TITLE
PHP nightly tests are broken

### ISSUE THREAD

**Issue by olegabr** [qcubed/framework#953]
See here: https://travis-ci.org/qcubed/framework/jobs/120404561

All error reasons are similar to this one:
```
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; TestSuite has a deprecated constructor in /home/travis/build/qcubed/framework/vendor/lastcraft/simpletest/test_case.php on line 477
```

**Comment by spekary** [comment]
Looks like its time to convert to PHPUnit. SimpleTest has not been changed in years. Yes?

**Comment by olegabr** [comment]
Yes. The last release is dated by 23/01/2012

**Comment by spekary** [comment]
I have pushed bugfix-UnitTests. It incorporates PHPUnit and runs all the current tests from the QCubed startup page. If someone could please jump in and do the work for the travis build, I would appreciate it. I will be out a few days.

The version I checked in uses some customizations to make PHP Unit work in an html page. By default it works from the command line, so that it hopefully will not be too difficult to incorporate that into the travis build. The setup process will probably be very different.
