### ISSUE TITLE
Determine if control value changed

### ISSUE THREAD

**Issue by kpirbhai** [qcubed/framework#978]
I'm wanting to add some functionality to QControl so that I can determine if the control value has actually changed by checking 'defaultValue' against 'value' using javascript.

The problem I have it that I honestly have no idea how to grab the value being returned from my JavaScript function from inside of QCubed.

My function is:
```
function ctrlValueChanged($strControlId) {
    var ctrl = document.getElementById($strControlId);
    if (ctrl.value != ctrl.defaultValue) {
        return true;
    } else {
        return false;
    }
}

```

And I'm calling it in QControl as:
```
                public function ValueHasChanged() {
                    return QApplication::ExecuteJsFunction('ctrlValueChanged', $this->ControlId);
                }
```
No value is returned. Any help would be greatly appreciated!

**Comment by spekary** [comment]
You can't return values from just Javascript. Values come back into QCubed in 2 ways: through a server post or through an Ajax post. You could also do it through a direct json connection, but that is outside of QCubed.

The key thing is that the javascript side must take some action and effort to send data back to the server. Its not easy, and not free. It involves dealing with the asynchronous nature of ajax too. Most of qcubed.js is designed to make this easier.

QCubed is designed to keep the value of the html controls in sync with the PHP controls. However, it doesn't do that on every click or key event. It does a synchronization whenever you ask for information, like through an event handler (AddAction (new QClickEvent(), ...) for example). Before it processes the action, it syncs the data so that the internal state is the same as what you see.

Perhaps describe what you are doing. If you just want to do something when your control changes, then just do:
```
$objControl->AddAction (new QChangeEvent(), new QAjaxAction('myHandler'));
```
If that won't work for you, describe more what you are trying to do. The key is to understand at what point in your program you need the information.

**Comment by kpirbhai** [comment]
I'm attempting to know if any of the control values have been changed to prevent a user from leaving a page that has not been saved if the data has changed.

Was also thinking of using this in order to prevent saving to the database if the user clicks "Submit" but hasn't actually changed anything.

**Comment by spekary** [comment]
> I'm attempting to know if any of the control values have been changed to prevent a user from leaving a page that has not been saved if the data has changed.

Just do something like
```
        var objFormElements = $j('#' + strForm).find('input,select,textarea');
objFormElements.each(function(i) {
// check for a change
});
```

The thing is, what is going to trigger you checking this? All your scenarios are things that are best handled in pure javascript. Trying to get this information sent back to the server will be asynchronous, and by the time you get a chance to do anything about a problem, the browser will have already moved on.
